[project]
name = "agentic-coding"
version = "0.1.0"
description = ""
authors = [
    {name = "Pradeep Kumar",email = "webreinvent@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autogen-agentchat (>=0.5.7,<0.6.0)",
    "autogen-ext[openai] (>=0.5.7,<0.6.0)",
    "python-dotenv (>=1.0.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
